# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180131_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'company'), (2, 'user')], default=2),
        ),
    ]
