# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180222_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='categoriestranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='categoriestranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='CategoriesTranslation',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
