# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180309_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(default='default.png', upload_to='files/'),
        ),
    ]
