# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180404_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='email',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='phone',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
