# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180404_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='email',
            field=models.EmailField(default='azam.mamatmurodov@gmail.com', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='phone',
            field=models.CharField(default=998389478, max_length=60),
            preserve_default=False,
        ),
    ]
