# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20180407_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(max_length=60, verbose_name='Name on card')),
                ('cart_number', models.CharField(max_length=60, verbose_name='Card number')),
                ('expiration_date', models.DateField(default=datetime.datetime(2018, 4, 18, 10, 29, 48, 549317, tzinfo=utc))),
                ('billing_address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
