# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 10:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_paymentcards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcards',
            options={'verbose_name': 'Payment method', 'verbose_name_plural': 'Payment methods'},
        ),
        migrations.AddField(
            model_name='paymentcards',
            name='holder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentcards',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 18, 10, 59, 47, 247928, tzinfo=utc)),
        ),
    ]
