# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 09:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20180413_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcards',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 23, 9, 36, 12, 685945, tzinfo=utc)),
        ),
    ]
