# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20180413_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcards',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentcards',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 23, 10, 29, 8, 374847, tzinfo=utc)),
        ),
    ]
