# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 07:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20180413_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcards',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 28, 7, 45, 31, 54343, tzinfo=utc)),
        ),
    ]
