# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20180418_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcards',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 28, 11, 13, 42, 189480, tzinfo=utc)),
        ),
    ]
