# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 12:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20180424_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcards',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 4, 12, 1, 57, 572043, tzinfo=utc)),
        ),
    ]
