# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 14:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20180424_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcards',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2030, 2, 3, 10, 10, 2)),
        ),
    ]
