# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='extra_attrs',
            field=models.CharField(default='', max_length=60, verbose_name='Css class'),
            preserve_default=False,
        ),
    ]
