# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menu_extra_attrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='extra_attrs',
        ),
    ]
