# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180222_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='bannertranslation',
            name='image',
            field=models.ImageField(upload_to='banners/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='bannertranslation',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bannertranslation',
            name='slug',
            field=models.SlugField(max_length=60, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='menutranslation',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='menutranslation',
            name='slug',
            field=models.SlugField(max_length=60, verbose_name='Slug'),
        ),
    ]
