# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 11:32
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180310_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticFooterPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[(('clients', 'For clients'), ('partners', 'For partners'))], max_length=12)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StaticFooterPageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('slug', models.SlugField(max_length=60, verbose_name='Slug')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.StaticFooterPage')),
            ],
            options={
                'verbose_name': 'static footer page Translation',
                'db_table': 'main_staticfooterpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='staticfooterpagetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
