# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180424_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticfooterpage',
            old_name='target_type',
            new_name='user_type',
        ),
    ]
