# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180426_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticfooterpage',
            name='user_type',
        ),
        migrations.AddField(
            model_name='staticfooterpage',
            name='target_type',
            field=models.IntegerField(blank=True, choices=[(0, 'For clients'), (1, 'For partners')], null=True),
        ),
    ]
