# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-24 10:06
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180224_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
