# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20180301_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'color Translation',
                'db_table': 'products_color_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.RenameModel(
            old_name='ProductColor',
            new_name='Color',
        ),
        migrations.AddField(
            model_name='colortranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.Color'),
        ),
        migrations.AlterUniqueTogether(
            name='colortranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
