# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20180301_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='colortranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Color Translation'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
