# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20180301_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='volume',
        ),
    ]
