# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20180301_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.CharField(max_length=120),
        ),
    ]
