# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-23 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_product_is_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='default.png', upload_to='products/', verbose_name='Image'),
        ),
    ]
