# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20180326_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_image',
            field=models.CharField(choices=[('image_0', 'First image'), ('image_1', 'Second image'), ('image_2', 'Third image')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_0',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
