# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_auto_20180326_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_image',
            field=models.CharField(choices=[('image_0', 'First image'), ('image_1', 'Second image'), ('image_2', 'Third image')], default='image_0', max_length=60),
        ),
    ]
