# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('products', '0047_auto_20180326_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
