# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 07:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180307_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 12, 56, 3, 515989)),
        ),
    ]
