# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180307_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина товара', 'verbose_name_plural': 'Корзина товара'},
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(default='', max_length=60, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'Доступно'), (1, 'Ожидание оплаты'), (2, 'Оплата завершена'), (3, 'Отменен'), (4, 'Доставлен')], default=0),
        ),
    ]
