# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Order Id'),
        ),
    ]
