# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180309_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_unique_id',
        ),
    ]
