# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20180309_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_unique_id',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True, verbose_name='Order Id'),
        ),
    ]
