# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20180309_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_unique_id',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True, verbose_name='Номер заказа'),
        ),
    ]
