# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20180430_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.TextField(blank=True, null=True),
        ),
    ]
