# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-24 19:53
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180523_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.FloatField(default=Decimal('25000')),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('9_15', '9:00 - 15:00'), ('15_21', '15:00 - 21:00')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='need_porter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('uzcard', 'Uzcard'), ('payme', 'Payme'), ('cash_on_delivery', 'Оплата при доставке')], default='uzcard', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='products_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_weight',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'Доступно'), (1, 'Ожидание оплаты'), (2, 'Оплата завершена'), (3, 'Отменен'), (4, 'Доставлен'), (-1, 'В процессе')], default=0),
        ),
    ]
