# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-26 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20180526_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(choices=[('uzcard', 'Uzcard'), ('payme', 'Payme'), ('cash_on_delivery', 'Оплата при доставке')], default='uzcard', max_length=40, unique=True),
        ),
    ]
