# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-26 10:06
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20180526_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='logo',
            field=filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
    ]
