# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20180526_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='porter_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
