# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_porter_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='porter_price',
            new_name='porter_work_price',
        ),
    ]
