# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20180601_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_time',
            field=models.DateTimeField(null=True),
        ),
    ]
