# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brands'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
    ]
