# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-24 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_variation_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='volume',
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, choices=[('kg', 'KG'), ('l', 'Litr')], max_length=12, null=True, verbose_name='Volume type'),
        ),
    ]
