# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 14:08
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180227_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='category',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
