# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20180301_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
