# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20180301_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.VolumeType'),
        ),
        migrations.AlterField(
            model_name='volumetypetranslation',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
