# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20180301_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
