# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20180301_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
