# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Is recommended'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.VolumeType', verbose_name='Is recommended'),
        ),
    ]
