# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_0',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image0', to=settings.FILER_IMAGE_MODEL, verbose_name='First image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image1', to=settings.FILER_IMAGE_MODEL, verbose_name='Second image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image2', to=settings.FILER_IMAGE_MODEL, verbose_name='Third image'),
        ),
    ]
