# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-14 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_product_prop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytranslation',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Name'),
        ),
    ]
