# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-14 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_auto_20180614_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Feature',
        ),
        migrations.RenameModel(
            old_name='PropertyTranslation',
            new_name='FeatureTranslation',
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='featuretranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Feature Translation'},
        ),
        migrations.AlterModelTable(
            name='featuretranslation',
            table='products_feature_translation',
        ),
    ]
